/*
**  Defined names for ISO chars seen as integers
*/
#define BLANK    32  /* ISO SPACE */
#define DIG0     48  /* ISO '0' */
#define DIG1     49  /* ISO '1' */
#define DIG2     50  /* ISO '2' */
#define DIG3     51  /* ISO '3' */
#define DIG4     52  /* ISO '4' */
#define DIG5     53  /* ISO '5' */
#define DIG6     54  /* ISO '6' */
#define DIG7     55  /* ISO '7' */
#define DIG8     56  /* ISO '8' */
#define DIG9     57  /* ISO '9' */
#define LETA     97  /* ISO 'a' */
#define LETB     98  /* ISO 'b' */
#define LETC     99  /* ISO 'c' */
#define LETD     100     /* ISO 'd' */
#define LETE     101     /* ISO 'e' */
#define LETF     102     /* ISO 'f' */
#define LETG     103     /* ISO 'g' */
#define LETH     104     /* ISO 'h' */
#define LETI     105     /* ISO 'i' */
#define LETJ     106     /* ISO 'j' */
#define LETK     107     /* ISO 'k' */
#define LETL     108     /* ISO 'l' */
#define LETM     109     /* ISO 'm' */
#define LETN     110     /* ISO 'n' */
#define LETO     111     /* ISO 'o' */
#define LETP     112     /* ISO 'p' */
#define LETQ     113     /* ISO 'q' */
#define LETR     114     /* ISO 'r' */
#define LETS     115     /* ISO 's' */
#define LETT     116     /* ISO 't' */
#define LETU     117     /* ISO 'u' */
#define LETV     118     /* ISO 'v' */
#define LETW     119     /* ISO 'w' */
#define LETX     120     /* ISO 'x' */
#define LETY     121     /* ISO 'y' */
#define LETZ     122     /* ISO 'z' */
#define CAPA     65  /* ISO 'A' */
#define CAPB     66  /* ISO 'B' */
#define CAPC     67  /* ISO 'C' */
#define CAPD     68  /* ISO 'D' */
#define CAPE     69  /* ISO 'E' */
#define CAPF     70  /* ISO 'F' */
#define CAPG     71  /* ISO 'G' */
#define CAPH     72  /* ISO 'H' */
#define CAPI     73  /* ISO 'I' */
#define CAPJ     74  /* ISO 'J' */
#define CAPK     75  /* ISO 'K' */
#define CAPL     76  /* ISO 'L' */
#define CAPM     77  /* ISO 'M' */
#define CAPN     78  /* ISO 'N' */
#define CAPO     79  /* ISO 'O' */
#define CAPP     80  /* ISO 'P' */
#define CAPQ     81  /* ISO 'Q' */
#define CAPR     82  /* ISO 'R' */
#define CAPS     83  /* ISO 'S' */
#define CAPT     84  /* ISO 'T' */
#define CAPU     85  /* ISO 'U' */
#define CAPV     86  /* ISO 'V' */
#define CAPW     87  /* ISO 'W' */
#define CAPX     88  /* ISO 'X' */
#define CAPY     89  /* ISO 'Y' */
#define CAPZ     90  /* ISO 'Z' */
#define EXCLAM   33  /* ISO '!' */
#define DQUOTE   34  /* ISO '"' */
#define SHARP    35  /* ISO '#' */
#define DOLLAR   36  /* ISO '$' */
#define PERCENT  37  /* ISO '%' */
#define AMPER    38  /* ISO '&' */
#define SQUOTE   39  /* ISO ''' */
#define LPAREN   40  /* ISO '(' */
#define RPAREN   41  /* ISO ')' */
#define STAR     42  /* ISO '*' */
#define PLUS     43  /* ISO '+' */
#define COMMA    44  /* ISO ',' */
#define MINUS    45  /* ISO '-' */
#define PERIOD   46  /* ISO '.' */
#define SLASH    47  /* ISO '/' */
#define COLON    58  /* ISO ':' */
#define SEMICOL  59  /* ISO ';' */
#define LESS     60  /* ISO '<' */
#define EQUALS   61  /* ISO '=' */
#define GREATER  62  /* ISO '>' */
#define QUESTION 63  /* ISO '?' */
#define ATSIGN   64  /* ISO '@' */
#define LBRACK   91  /* ISO '[' */
#define BAKSLASH 92  /* ISO '\' */
#define RBRACK   93  /* ISO ']' */
#define CFLEX    94  /* ISO '^' */
#define USCORE   95  /* ISO '_' */
#define GRAVE    96  /* ISO '`' */
#define LBRACE   123     /* ISO '{' */
#define BAR  124     /* ISO '|' */
#define RBRACE   125     /* ISO '}' */
#define CTILDE   126     /* ISO '~' */
#define NUL  0   /* ISO NUL */
#define CTLA     1   /* ISO SOH */
#define CTLB     2   /* ISO STX */
#define CTLC     3   /* ISO ETX */
#define CTLD     4   /* ISO EOT */
#define CTLE     5   /* ISO ENQ */
#define CTLF     6   /* ISO ACK */
#define CTLG     7   /* ISO BEL */
#define CTLH     8   /* ISO BS */
#define CTLI     9   /* ISO HT */
#define CTLJ     10  /* ISO LF */
#define CTLK     11  /* ISO VT */
#define CTLL     12  /* ISO FF */
#define CTLM     13  /* ISO CR */
#define CTLN     14  /* ISO SO */
#define CTLO     15  /* ISO SI */
#define CTLP     16  /* ISO DLE */
#define CTLQ     17  /* ISO DC1 */
#define CTLR     18  /* ISO DC2 */
#define CTLS     19  /* ISO DC3 */
#define CTLT     20  /* ISO DC4 */
#define CTLU     21  /* ISO NAK */
#define CTLV     22  /* ISO SYN */
#define CTLW     23  /* ISO ETB */
#define CTLX     24  /* ISO CAN */
#define CTLY     25  /* ISO EM */
#define CTLZ     26  /* ISO SUB */
#define ESC  27  /* ISO ESC */
#define DEL  127     /* ISO DEL */
#define ENDSTR   NUL     /* ISO NUL */
#define TAB  CTLI    /* ISO HT */
#define NEWLINE  CTLJ    /* ISO LF */
#define RETURN   CTLM    /* ISO CR */
#define ENDFILE  CTLY    /* ISO EM */
