procedure SIZBYTE       ( var ret : integer;
                          x : byte;
                          y : byte);             nonpascal;
procedure SIZCOLTYPE    ( var ret : integer;
                          x : coltype;
                          y : coltype);          nonpascal;
procedure SIZFDPOINTER  ( var ret : integer;
                          x : fdpointer;
                          y : fdpointer);        nonpascal;
procedure SIZFIELDINDEX ( var ret : integer;
                          x : fieldindex;
                          y : fieldindex);       nonpascal;
procedure SIZFILEDESC   ( var ret : integer;
                          x : filedesc;
                          y : filedesc);         nonpascal;
procedure SIZISOCHAR    ( var ret : integer;
                          x : isochar;
                          y : isochar);          nonpascal;
procedure SIZMODEINDEX  ( var ret : integer;
                          x : modeindex;
                          y : modeindex);        nonpascal;
procedure SIZROWTYPE    ( var ret : integer;
                          x : rowtype;
                          y : rowtype);          nonpascal;
procedure SIZSMALLINT   ( var ret : integer;
                          x : smallint;
                          y : smallint);         nonpascal;
procedure SIZCHSTRING   ( var ret : integer;
                          var a : chstring);     nonpascal;
procedure SIZCHTABLE    ( var ret : integer;
                          var a : chtable);      nonpascal;
procedure SIZIMTYPE     ( var ret : integer;
                          var a : imtype);       nonpascal;
procedure SIZITABLE     ( var ret : integer;
                          var a : itable);       nonpascal;
procedure SIZMODEARRAY  ( var ret : integer;
                          var a : modearray);    nonpascal;
procedure SIZTEXTLIT    ( var ret : integer;
                          var a : textlit);      nonpascal;
procedure CRASHOUT      ( var ret : integer);    nonpascal;

