procedure SIZBYTE       ( var ret : integer;
                          x : byte;
                          y : byte);             external;
procedure SIZCOLTYPE    ( var ret : integer;
                          x : coltype;
                          y : coltype);          external;
procedure SIZFDPOINTER  ( var ret : integer;
                          x : fdpointer;
                          y : fdpointer);        external;
procedure SIZFIELDINDEX ( var ret : integer;
                          x : fieldindex;
                          y : fieldindex);       external;
procedure SIZFILEDESC   ( var ret : integer;
                          x : filedesc;
                          y : filedesc);         external;
procedure SIZISOCHAR    ( var ret : integer;
                          x : isochar;
                          y : isochar);          external;
procedure SIZMODEINDEX  ( var ret : integer;
                          x : modeindex;
                          y : modeindex);        external;
procedure SIZROWTYPE    ( var ret : integer;
                          x : rowtype;
                          y : rowtype);          external;
procedure SIZSMALLINT   ( var ret : integer;
                          x : smallint;
                          y : smallint);         external;
procedure SIZCHSTRING   ( var ret : integer;
                          var a : chstring);     external;
procedure SIZCHTABLE    ( var ret : integer;
                          var a : chtable);      external;
procedure SIZIMTYPE     ( var ret : integer;
                          var a : imtype);       external;
procedure SIZITABLE     ( var ret : integer;
                          var a : itable);       external;
procedure SIZMODEARRAY  ( var ret : integer;
                          var a : modearray);    external;
procedure SIZTEXTLIT    ( var ret : integer;
                          var a : textlit);      external;
procedure CRASHOUT      ( var ret : integer);    external;

